Repository canonical/charmcraft, pull requests merged in 2025-01, with the labels that each got.

#2106 fix: exit with 0 if re-publishing the same library
  charmcraft/application/commands/store.py
  docs/reference/changelog.rst
  tests/unit/commands/test_store.py
Labels: rebase

#2104 docs: update platforms reference
  docs/reference/platforms.rst
Labels: squash

#2121 chore(release): merge 3.3.2 to main
  charmcraft/application/commands/init.py
  charmcraft/application/commands/store.py
  charmcraft/application/commands/test.py
  charmcraft/templates/init-kubernetes/spread.yaml.j2
  charmcraft/templates/init-kubernetes/tests/spread/general/integration/task.yaml.j2
  charmcraft/templates/init-kubernetes/tests/spread/lib/cloud-config.yaml.j2
  charmcraft/templates/init-kubernetes/tests/spread/lib/test-helpers.sh.j2
  charmcraft/templates/init-kubernetes/tests/spread/lib/tools/retry.j2
  charmcraft/templates/init-machine/spread.yaml.j2
  charmcraft/templates/init-machine/tests/spread/general/integration/task.yaml.j2
  charmcraft/templates/init-machine/tests/spread/lib/cloud-config.yaml.j2
  charmcraft/templates/init-machine/tests/spread/lib/test-helpers.sh.j2
  charmcraft/templates/init-simple/spread.yaml.j2
  charmcraft/templates/init-simple/tests/spread/general/integration/task.yaml.j2
  charmcraft/templates/init-simple/tests/spread/lib/cloud-config.yaml.j2
  charmcraft/templates/init-simple/tests/spread/lib/test-helpers.sh.j2
  charmcraft/templates/init-simple/tests/spread/lib/tools/retry.j2
  docs/conf.py
  docs/howto/build-guides/index.rst
  docs/howto/build-guides/select-platforms.rst
  docs/howto/flask-async.rst
  docs/howto/manage-bundles.rst
  docs/howto/manage-charms.rst
  docs/howto/manage-extensions.rst
  docs/howto/manage-resources.rst
  docs/howto/manage-revisions.rst
  docs/index.rst
  docs/reference/changelog.rst
  docs/reference/files/actions-yaml-file.rst
  docs/reference/files/bundle-yaml-file.rst
  docs/reference/files/charmcraft-sample-charm.yaml
  docs/reference/files/charmcraft-yaml-file.rst
  docs/reference/index.rst
  docs/reference/platforms.rst
  docs/reuse/links.txt
  docs/tutorial/flask.rst
  tests/integration/commands/test_init.py
  tests/unit/commands/test_store.py
Labels: merge

#2115 Add release notes page and release notes for 3.4 specifically.
  common.mk
  docs/index.rst
  docs/reference/changelog.rst
  docs/release-notes/charmcraft-3.4.0.rst
  docs/release-notes/index.rst
  docs/reuse/links.txt
Labels: rebase
